/**
 * Referentiels fiche salarie — valeurs exactes de docs/referentiels-fiche-salarie.md.
 * Aucune valeur inventee, traduite ou corrigee.
 */

export const PAYS = [
  { ordre: 1, codeIso: 'MA', libelle: 'Maroc' },
  { ordre: 2, codeIso: 'AF', libelle: 'Afghanistan' },
  { ordre: 3, codeIso: 'ZA', libelle: 'Afrique du Sud' },
  { ordre: 4, codeIso: 'AL', libelle: 'Albanie' },
  { ordre: 5, codeIso: 'DZ', libelle: 'Algérie' },
  { ordre: 6, codeIso: 'DE', libelle: 'Allemagne' },
  { ordre: 7, codeIso: 'AD', libelle: 'Andorre' },
  { ordre: 8, codeIso: 'AO', libelle: 'Angola' },
  { ordre: 9, codeIso: 'AG', libelle: 'Antigua-et-Barbuda' },
  { ordre: 10, codeIso: 'SA', libelle: 'Arabie saoudite' },
  { ordre: 11, codeIso: 'AR', libelle: 'Argentine' },
  { ordre: 12, codeIso: 'AM', libelle: 'Arménie' },
  { ordre: 13, codeIso: 'AU', libelle: 'Australie' },
  { ordre: 14, codeIso: 'AT', libelle: 'Autriche' },
  { ordre: 15, codeIso: 'AZ', libelle: 'Azerbaïdjan' },
  { ordre: 16, codeIso: 'BS', libelle: 'Bahamas' },
  { ordre: 17, codeIso: 'BH', libelle: 'Bahreïn' },
  { ordre: 18, codeIso: 'BD', libelle: 'Bangladesh' },
  { ordre: 19, codeIso: 'BB', libelle: 'Barbade' },
  { ordre: 20, codeIso: 'BE', libelle: 'Belgique' },
  { ordre: 21, codeIso: 'BZ', libelle: 'Belize' },
  { ordre: 22, codeIso: 'BJ', libelle: 'Bénin' },
  { ordre: 23, codeIso: 'BT', libelle: 'Bhoutan' },
  { ordre: 24, codeIso: 'BY', libelle: 'Biélorussie' },
  { ordre: 25, codeIso: 'BO', libelle: 'Bolivie' },
  { ordre: 26, codeIso: 'BA', libelle: 'Bosnie-Herzégovine' },
  { ordre: 27, codeIso: 'BW', libelle: 'Botswana' },
  { ordre: 28, codeIso: 'BR', libelle: 'Brésil' },
  { ordre: 29, codeIso: 'BN', libelle: 'Brunei' },
  { ordre: 30, codeIso: 'BG', libelle: 'Bulgarie' },
  { ordre: 31, codeIso: 'BF', libelle: 'Burkina Faso' },
  { ordre: 32, codeIso: 'BI', libelle: 'Burundi' },
  { ordre: 33, codeIso: 'KH', libelle: 'Cambodge' },
  { ordre: 34, codeIso: 'CM', libelle: 'Cameroun' },
  { ordre: 35, codeIso: 'CA', libelle: 'Canada' },
  { ordre: 36, codeIso: 'CV', libelle: 'Cap-Vert' },
  { ordre: 37, codeIso: 'CL', libelle: 'Chili' },
  { ordre: 38, codeIso: 'CN', libelle: 'Chine' },
  { ordre: 39, codeIso: 'CY', libelle: 'Chypre' },
  { ordre: 40, codeIso: 'CO', libelle: 'Colombie' },
  { ordre: 41, codeIso: 'KM', libelle: 'Comores' },
  { ordre: 42, codeIso: 'CG', libelle: 'Congo-Brazzaville' },
  { ordre: 43, codeIso: 'CD', libelle: 'Congo-Kinshasa' },
  { ordre: 44, codeIso: 'KP', libelle: 'Corée du Nord' },
  { ordre: 45, codeIso: 'KR', libelle: 'Corée du Sud' },
  { ordre: 46, codeIso: 'CR', libelle: 'Costa Rica' },
  { ordre: 47, codeIso: 'CI', libelle: 'Côte d\u2019Ivoire' },
  { ordre: 48, codeIso: 'HR', libelle: 'Croatie' },
  { ordre: 49, codeIso: 'CU', libelle: 'Cuba' },
  { ordre: 50, codeIso: 'DK', libelle: 'Danemark' },
  { ordre: 51, codeIso: 'DJ', libelle: 'Djibouti' },
  { ordre: 52, codeIso: 'DM', libelle: 'Dominique' },
  { ordre: 53, codeIso: 'EG', libelle: 'Égypte' },
  { ordre: 54, codeIso: 'AE', libelle: 'Émirats arabes unis' },
  { ordre: 55, codeIso: 'EC', libelle: 'Équateur' },
  { ordre: 56, codeIso: 'ER', libelle: 'Érythrée' },
  { ordre: 57, codeIso: 'ES', libelle: 'Espagne' },
  { ordre: 58, codeIso: 'EE', libelle: 'Estonie' },
  { ordre: 59, codeIso: 'SZ', libelle: 'Eswatini' },
  { ordre: 60, codeIso: 'US', libelle: 'États-Unis' },
  { ordre: 61, codeIso: 'ET', libelle: 'Éthiopie' },
  { ordre: 62, codeIso: 'FJ', libelle: 'Fidji' },
  { ordre: 63, codeIso: 'FI', libelle: 'Finlande' },
  { ordre: 64, codeIso: 'FR', libelle: 'France' },
  { ordre: 65, codeIso: 'GA', libelle: 'Gabon' },
  { ordre: 66, codeIso: 'GM', libelle: 'Gambie' },
  { ordre: 67, codeIso: 'GE', libelle: 'Géorgie' },
  { ordre: 68, codeIso: 'GH', libelle: 'Ghana' },
  { ordre: 69, codeIso: 'GR', libelle: 'Grèce' },
  { ordre: 70, codeIso: 'GD', libelle: 'Grenade' },
  { ordre: 71, codeIso: 'GT', libelle: 'Guatemala' },
  { ordre: 72, codeIso: 'GN', libelle: 'Guinée' },
  { ordre: 73, codeIso: 'GQ', libelle: 'Guinée équatoriale' },
  { ordre: 74, codeIso: 'GW', libelle: 'Guinée-Bissau' },
  { ordre: 75, codeIso: 'GY', libelle: 'Guyana' },
  { ordre: 76, codeIso: 'HT', libelle: 'Haïti' },
  { ordre: 77, codeIso: 'HN', libelle: 'Honduras' },
  { ordre: 78, codeIso: 'HU', libelle: 'Hongrie' },
  { ordre: 79, codeIso: 'MH', libelle: 'Îles Marshall' },
  { ordre: 80, codeIso: 'SB', libelle: 'Îles Salomon' },
  { ordre: 81, codeIso: 'IN', libelle: 'Inde' },
  { ordre: 82, codeIso: 'ID', libelle: 'Indonésie' },
  { ordre: 83, codeIso: 'IQ', libelle: 'Irak' },
  { ordre: 84, codeIso: 'IR', libelle: 'Iran' },
  { ordre: 85, codeIso: 'IE', libelle: 'Irlande' },
  { ordre: 86, codeIso: 'IS', libelle: 'Islande' },
  { ordre: 87, codeIso: 'IL', libelle: 'Israël' },
  { ordre: 88, codeIso: 'IT', libelle: 'Italie' },
  { ordre: 89, codeIso: 'JM', libelle: 'Jamaïque' },
  { ordre: 90, codeIso: 'JP', libelle: 'Japon' },
  { ordre: 91, codeIso: 'JO', libelle: 'Jordanie' },
  { ordre: 92, codeIso: 'KZ', libelle: 'Kazakhstan' },
  { ordre: 93, codeIso: 'KE', libelle: 'Kenya' },
  { ordre: 94, codeIso: 'KG', libelle: 'Kirghizstan' },
  { ordre: 95, codeIso: 'KI', libelle: 'Kiribati' },
  { ordre: 96, codeIso: 'KW', libelle: 'Koweït' },
  { ordre: 97, codeIso: 'LA', libelle: 'Laos' },
  { ordre: 98, codeIso: 'LS', libelle: 'Lesotho' },
  { ordre: 99, codeIso: 'LV', libelle: 'Lettonie' },
  { ordre: 100, codeIso: 'LB', libelle: 'Liban' },
  { ordre: 101, codeIso: 'LR', libelle: 'Liberia' },
  { ordre: 102, codeIso: 'LY', libelle: 'Libye' },
  { ordre: 103, codeIso: 'LI', libelle: 'Liechtenstein' },
  { ordre: 104, codeIso: 'LT', libelle: 'Lituanie' },
  { ordre: 105, codeIso: 'LU', libelle: 'Luxembourg' },
  { ordre: 106, codeIso: 'MK', libelle: 'Macédoine du Nord' },
  { ordre: 107, codeIso: 'MG', libelle: 'Madagascar' },
  { ordre: 108, codeIso: 'MY', libelle: 'Malaisie' },
  { ordre: 109, codeIso: 'MW', libelle: 'Malawi' },
  { ordre: 110, codeIso: 'MV', libelle: 'Maldives' },
  { ordre: 111, codeIso: 'ML', libelle: 'Mali' },
  { ordre: 112, codeIso: 'MT', libelle: 'Malte' },
  { ordre: 113, codeIso: 'MU', libelle: 'Maurice' },
  { ordre: 114, codeIso: 'MR', libelle: 'Mauritanie' },
  { ordre: 115, codeIso: 'MX', libelle: 'Mexique' },
  { ordre: 116, codeIso: 'FM', libelle: 'Micronésie' },
  { ordre: 117, codeIso: 'MD', libelle: 'Moldavie' },
  { ordre: 118, codeIso: 'MC', libelle: 'Monaco' },
  { ordre: 119, codeIso: 'MN', libelle: 'Mongolie' },
  { ordre: 120, codeIso: 'ME', libelle: 'Monténégro' },
  { ordre: 121, codeIso: 'MZ', libelle: 'Mozambique' },
  { ordre: 122, codeIso: 'MM', libelle: 'Myanmar (Birmanie)' },
  { ordre: 123, codeIso: 'NA', libelle: 'Namibie' },
  { ordre: 124, codeIso: 'NR', libelle: 'Nauru' },
  { ordre: 125, codeIso: 'NP', libelle: 'Népal' },
  { ordre: 126, codeIso: 'NI', libelle: 'Nicaragua' },
  { ordre: 127, codeIso: 'NE', libelle: 'Niger' },
  { ordre: 128, codeIso: 'NG', libelle: 'Nigeria' },
  { ordre: 129, codeIso: 'NO', libelle: 'Norvège' },
  { ordre: 130, codeIso: 'NZ', libelle: 'Nouvelle-Zélande' },
  { ordre: 131, codeIso: 'OM', libelle: 'Oman' },
  { ordre: 132, codeIso: 'UG', libelle: 'Ouganda' },
  { ordre: 133, codeIso: 'UZ', libelle: 'Ouzbékistan' },
  { ordre: 134, codeIso: 'PK', libelle: 'Pakistan' },
  { ordre: 135, codeIso: 'PW', libelle: 'Palaos' },
  { ordre: 136, codeIso: 'PS', libelle: 'Palestine' },
  { ordre: 137, codeIso: 'PA', libelle: 'Panama' },
  { ordre: 138, codeIso: 'PG', libelle: 'Papouasie-Nouvelle-Guinée' },
  { ordre: 139, codeIso: 'PY', libelle: 'Paraguay' },
  { ordre: 140, codeIso: 'NL', libelle: 'Pays-Bas' },
  { ordre: 141, codeIso: 'PE', libelle: 'Pérou' },
  { ordre: 142, codeIso: 'PH', libelle: 'Philippines' },
  { ordre: 143, codeIso: 'PL', libelle: 'Pologne' },
  { ordre: 144, codeIso: 'PT', libelle: 'Portugal' },
  { ordre: 145, codeIso: 'QA', libelle: 'Qatar' },
  { ordre: 146, codeIso: 'CF', libelle: 'République centrafricaine' },
  { ordre: 147, codeIso: 'DO', libelle: 'République dominicaine' },
  { ordre: 148, codeIso: 'RO', libelle: 'Roumanie' },
  { ordre: 149, codeIso: 'GB', libelle: 'Royaume-Uni' },
  { ordre: 150, codeIso: 'RU', libelle: 'Russie' },
  { ordre: 151, codeIso: 'RW', libelle: 'Rwanda' },
  { ordre: 152, codeIso: 'KN', libelle: 'Saint-Christophe-et-Niévès' },
  { ordre: 153, codeIso: 'SM', libelle: 'Saint-Marin' },
  { ordre: 154, codeIso: 'VA', libelle: 'Saint-Siège (Vatican)' },
  { ordre: 155, codeIso: 'VC', libelle: 'Saint-Vincent-et-les Grenadines' },
  { ordre: 156, codeIso: 'LC', libelle: 'Sainte-Lucie' },
  { ordre: 157, codeIso: 'SV', libelle: 'Salvador' },
  { ordre: 158, codeIso: 'WS', libelle: 'Samoa' },
  { ordre: 159, codeIso: 'ST', libelle: 'Sao Tomé-et-Principe' },
  { ordre: 160, codeIso: 'SN', libelle: 'Sénégal' },
  { ordre: 161, codeIso: 'RS', libelle: 'Serbie' },
  { ordre: 162, codeIso: 'SC', libelle: 'Seychelles' },
  { ordre: 163, codeIso: 'SL', libelle: 'Sierra Leone' },
  { ordre: 164, codeIso: 'SG', libelle: 'Singapour' },
  { ordre: 165, codeIso: 'SK', libelle: 'Slovaquie' },
  { ordre: 166, codeIso: 'SI', libelle: 'Slovénie' },
  { ordre: 167, codeIso: 'SO', libelle: 'Somalie' },
  { ordre: 168, codeIso: 'SD', libelle: 'Soudan' },
  { ordre: 169, codeIso: 'SS', libelle: 'Soudan du Sud' },
  { ordre: 170, codeIso: 'LK', libelle: 'Sri Lanka' },
  { ordre: 171, codeIso: 'SE', libelle: 'Suède' },
  { ordre: 172, codeIso: 'CH', libelle: 'Suisse' },
  { ordre: 173, codeIso: 'SR', libelle: 'Suriname' },
  { ordre: 174, codeIso: 'SY', libelle: 'Syrie' },
  { ordre: 175, codeIso: 'TJ', libelle: 'Tadjikistan' },
  { ordre: 176, codeIso: 'TZ', libelle: 'Tanzanie' },
  { ordre: 177, codeIso: 'TD', libelle: 'Tchad' },
  { ordre: 178, codeIso: 'CZ', libelle: 'Tchéquie' },
  { ordre: 179, codeIso: 'TH', libelle: 'Thaïlande' },
  { ordre: 180, codeIso: 'TL', libelle: 'Timor oriental' },
  { ordre: 181, codeIso: 'TG', libelle: 'Togo' },
  { ordre: 182, codeIso: 'TO', libelle: 'Tonga' },
  { ordre: 183, codeIso: 'TT', libelle: 'Trinité-et-Tobago' },
  { ordre: 184, codeIso: 'TN', libelle: 'Tunisie' },
  { ordre: 185, codeIso: 'TM', libelle: 'Turkménistan' },
  { ordre: 186, codeIso: 'TR', libelle: 'Turquie' },
  { ordre: 187, codeIso: 'TV', libelle: 'Tuvalu' },
  { ordre: 188, codeIso: 'UA', libelle: 'Ukraine' },
  { ordre: 189, codeIso: 'UY', libelle: 'Uruguay' },
  { ordre: 190, codeIso: 'VU', libelle: 'Vanuatu' },
  { ordre: 191, codeIso: 'VE', libelle: 'Venezuela' },
  { ordre: 192, codeIso: 'VN', libelle: 'Viêt Nam' },
  { ordre: 193, codeIso: 'YE', libelle: 'Yémen' },
  { ordre: 194, codeIso: 'ZM', libelle: 'Zambie' },
  { ordre: 195, codeIso: 'ZW', libelle: 'Zimbabwe' },
] as const;

export const TYPES_CONTRAT = [
  { code: 'CDI', libelle: 'Contrat à durée indéterminée' },
  { code: 'CDD', libelle: 'Contrat à durée déterminée' },
  { code: 'CTT', libelle: 'Contrat de travail temporaire' },
  { code: 'INT_CDI', libelle: 'Intérimaire — contrat à durée indéterminée' },
  { code: 'OBJ', libelle: 'Contrat à objet défini' },
  { code: 'STAGE', libelle: 'Convention de stage' },
  { code: 'MANDAT', libelle: 'Mandataire social' },
] as const;

export const MOTIFS_SORTIE = [
  { code: 'DEMISSION', libelle: 'Démission' },
  { code: 'LIC_FAUTE_SIMPLE', libelle: 'Licenciement pour faute simple' },
  { code: 'LIC_FAUTE_GRAVE', libelle: 'Licenciement pour faute grave' },
  { code: 'LIC_FAUTE_LOURDE', libelle: 'Licenciement pour faute lourde' },
  { code: 'LIC_ECONOMIQUE', libelle: 'Licenciement pour motif économique' },
  { code: 'FIN_CDD', libelle: 'Fin de contrat à durée déterminée' },
  { code: 'COMMUN_ACCORD', libelle: "Rupture d'un commun accord" },
  { code: 'RUPTURE_ESSAI', libelle: 'Rupture de la période d essai' },
  { code: 'RETRAITE_VOLONTAIRE', libelle: 'Départ volontaire à la retraite' },
  { code: 'RETRAITE_OFFICE', libelle: "Retraite d'office (limite d'âge)" },
  { code: 'FORCE_MAJEURE', libelle: 'Force majeure' },
  { code: 'DETACHEMENT', libelle: 'Départ en détachement' },
  { code: 'DECES', libelle: 'Décès, disparition' },
] as const;

export const STATUTS_PARTICULIERS = [{ code: 'IDMAJ', libelle: 'IDMAJ — ANAPEC' }] as const;

/** Code technique des lignes TAHFIZ propagees — jamais propose a la saisie. */
export const STATUT_TECHNIQUE_TAHFIZ = {
  code: 'TAHFIZ',
  libelle: 'TAHFIZ — exonération société',
} as const;

export const SITUATIONS_FAMILIALES = [
  { code: 'CELIBATAIRE', libelleMasculin: 'Célibataire', libelleFeminin: 'Célibataire' },
  { code: 'MARIE', libelleMasculin: 'Marié', libelleFeminin: 'Mariée' },
  { code: 'DIVORCE', libelleMasculin: 'Divorcé', libelleFeminin: 'Divorcée' },
  { code: 'VEUF', libelleMasculin: 'Veuf', libelleFeminin: 'Veuve' },
] as const;

export const LIENS_PARENTE = [
  { code: 'ENFANT', libelle: 'Enfant' },
  { code: 'CONJOINT', libelle: 'Conjoint' },
] as const;
